language: php
matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
      dist: precise
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
    - php: master
  allow_failures:
    - php: 7.4
    - php: nightly
    - php: master
before_script:
  - composer self-update
  - travis_retry composer install --prefer-source --no-interaction
